kind = "mobile"
previewPath = "/"
title = "SWAC App"
version = "1.0.0"
id = "artifacts/swac-app"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 19594

[services.development]
run = "pnpm --filter @workspace/swac-app run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/swac-app", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/swac-app", "run", "serve" ]

[services.env]
PORT = "19594"
BASE_PATH = "/"
